name: Deploy PHP App to Azure

on:
  push:
    branches:
      - desarrollo-nuevos-modulos # Asegúrate de que coincida con tu rama de trabajo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: plataforma-monitoreo-web
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: . # El punto indica que use la raíz del repositorio 
